BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
// Ignore Spelling: Upsert

using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize(Roles = StaticDetails.Role_Admin)]
	public class CompanyController : Controller
    {
		private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

		public CompanyController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Upsert(int? id)
        {
            Company company = new();
            if (id == null || id == 0)
            {
                return View(company);
            }

            company = _unitOfWork.CompanyRepository.Get(c => c.Id == id);
            return View(company);
        }
        [HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Upsert(Company company)
        {
            if (ModelState.IsValid)
            {
				if (company.Id == 0)
				{
					_unitOfWork.CompanyRepository.Add(company);
					TempData["success"] = "Company created successfully!";
				}
				else
				{
					_unitOfWork.CompanyRepository.Update(company);
					TempData["success"] = "Product updated successfully!";
				}

				_unitOfWork.Save();
				return RedirectToAction("Index");
			}
            return View(company);
        }

		#region API CALL
		[HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<Company> CompanyList = _unitOfWork.CompanyRepository.GetAll();
            return Json( new { companies = CompanyList } );
		}

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            Company CompanyToDelete = _unitOfWork.CompanyRepository.Get(c => c.Id == id);
			if (CompanyToDelete == null)
			{
				return Json(new { success = false, message = "Error while deleting!" });
			}

            _unitOfWork.CompanyRepository.Remove(CompanyToDelete);
            _unitOfWork.Save();

			return Json(new { success = true, message = "Delete successful!" });
		}
		#endregion
	}
}

BulkyWeb/Areas/Admin/Controllers/ProductController.cs
// Ignore Spelling: Upsert

using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Data;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize(Roles = StaticDetails.Role_Admin)]
    public class ProductController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		private readonly IWebHostEnvironment _webHostEnvironment;

		public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
		{
			_unitOfWork = unitOfWork;
			_webHostEnvironment = webHostEnvironment;
		}

		public IActionResult Index()
		{
			return View();
		}
		
		public IActionResult Upsert(int? id)
		{
			ProductVM productVM = new()
			{
				Product = new Product(),
				CategoryList = _unitOfWork.CategoryRepository.GetAll().Select(c => new SelectListItem
				{
					Text = c.Name,
					Value = c.Id.ToString(),
				}),
				CoverTypeList = _unitOfWork.CoverTypeRepository.GetAll().Select(ct => new SelectListItem
				{
					Text = ct.Name,
					Value = ct.Id.ToString(),
				}),
			};
			if (id == null || id == 0)
				return View(productVM);
			else
			{
				productVM.Product = _unitOfWork.ProductRepository.Get(p => p.Id == id);
				return View(productVM);
			}
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Upsert(ProductVM productVM, IFormFile? file)
		{
			if (ModelState.IsValid)
			{
				string wwwRootPath = _webHostEnvironment.WebRootPath;
				if (file != null)
				{
					string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
					string productPath = Path.Combine(wwwRootPath, @"images\product");

					if (!string.IsNullOrEmpty(productVM.Product.ImageUrl))
					{
						var oldImagePath = Path.Combine(wwwRootPath, productVM.Product.ImageUrl.TrimStart('\\'));

						if (System.IO.File.Exists(oldImagePath))
						{
							System.IO.File.Delete(oldImagePath);
						}
					}

					using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
					{
						file.CopyTo(fileStream);
					}

					productVM.Product.ImageUrl = @"\images\product\" + fileName;
				}

				if (productVM.Product.Id == 0)
				{
					_unitOfWork.ProductRepository.Add(productVM.Product);
					TempData["success"] = "Product created successfully!";
				}
				else
				{
					_unitOfWork.ProductRepository.Update(productVM.Product);
					TempData["success"] = "Product updated successfully!";
				}

				_unitOfWork.Save();
				return RedirectToAction("Index");
			}
			else
			{
				productVM.CategoryList = _unitOfWork.CategoryRepository.GetAll().Select(c => new SelectListItem
				{
					Text = c.Name,
					Value = c.Id.ToString(),
				});
				productVM.CoverTypeList = _unitOfWork.CoverTypeRepository.GetAll().Select(ct => new SelectListItem
				{
					Text = ct.Name,
					Value = ct.Id.ToString(),
				});
				return View(productVM);
			}
		}

		#region API CALL
		[HttpGet]
		public IActionResult GetAll()
		{
			IEnumerable<Product> ProductList = _unitOfWork.ProductRepository.GetAll(includeProperties: "Category,CoverType");
			return Json( new { products = ProductList } );
		}

		[HttpDelete]
		public IActionResult Delete(int? id)
		{
			var productToBeDeleted = _unitOfWork.ProductRepository.Get(p => p.Id == id);
			if (productToBeDeleted == null)
			{
				return Json(new { success = false, message = "Error while deleting!" });
			}

			var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, productToBeDeleted.ImageUrl.TrimStart('\\'));

			if (System.IO.File.Exists(oldImagePath))
			{
				System.IO.File.Delete(oldImagePath);
			}

			_unitOfWork.ProductRepository.Remove(productToBeDeleted);
			_unitOfWork.Save();

			return Json(new { success = true, message = "Delete successful!" });
		}
		#endregion
	}
}

BulkyWeb/Areas/Admin/Controllers/UserController.cs
using BulkyBook.DataAccess.Data;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = StaticDetails.Role_Admin)]
    public class UserController : Controller
    {
		private readonly ApplicationDbContext _context;
		private readonly UserManager<IdentityUser> _userManager;

		public UserController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
			_context = context;
			_userManager = userManager;
		}

		public IActionResult Index()
		{
			return View();
		}

        public IActionResult Update(string? Id)
        {
            if (Id == null || Id == "")
            {
                return View();
            }

			string roleId = _context.UserRoles.FirstOrDefault(u => u.UserId == Id).RoleId;

			ApplicationUserVM applicationUserVM = new()
			{
				ApplicationUser = _context.ApplicationUsers.Include(u => u.Company).FirstOrDefault(u => u.Id == Id),
				Companies = _context.Companies.Select(c => new SelectListItem { Text = c.Name, Value = c.Id.ToString() }),
				Roles = _context.Roles.Select(r => new SelectListItem { Text = r.Name, Value = r.Name }),
			};

			applicationUserVM.ApplicationUser.Role = _context.Roles.FirstOrDefault(r => r.Id == roleId).Name;

			return View(applicationUserVM);
		}
        [HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Update(ApplicationUserVM applicationUserVM)
        {
			string roleId = _context.UserRoles.FirstOrDefault(u => u.UserId == applicationUserVM.ApplicationUser.Id).RoleId;
			string oldRole = _context.Roles.FirstOrDefault(r => r.Id == roleId).Name;

			if (applicationUserVM.ApplicationUser.Role != oldRole)
			{
				ApplicationUser applicationUser = _context.ApplicationUsers.FirstOrDefault(u => u.Id == applicationUserVM.ApplicationUser.Id);
				if (applicationUserVM.ApplicationUser.Role == StaticDetails.Role_Company)
				{
					applicationUser.CompanyId = applicationUserVM.ApplicationUser.CompanyId;
				}
				if (oldRole == StaticDetails.Role_Company)
				{
					applicationUser.CompanyId = null;
				}

				_context.ApplicationUsers.Update(applicationUser);
				_context.SaveChanges();
				_userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
				_userManager.AddToRoleAsync(applicationUser, applicationUserVM.ApplicationUser.Role).GetAwaiter().GetResult();
			}

			TempData["success"] = "User updated successfully!";
			return RedirectToAction("Index");
		}

		#region API CALL
		[HttpGet]
        public IActionResult GetAll()
        {
            IEnumerable<ApplicationUser> UserList = _context.ApplicationUsers.Include(u => u.Company).ToList();
            
			var userRoles = _context.UserRoles.ToList();
			var roles = _context.Roles.ToList();

			foreach (ApplicationUser user in UserList)
            {
				var roleId = userRoles.FirstOrDefault(r => r.UserId == user.Id).RoleId;
				user.Role = roles.FirstOrDefault(r => r.Id == roleId).Name;

				if (user.Company == null)
				{
					user.Company = new Company()
					{
						Name = ""
					};
				}
			}

			return Json( new { users = UserList } );
        }

		[HttpPost]
		public IActionResult LockUnlock([FromBody]string id)
		{
			var user = _context.ApplicationUsers.FirstOrDefault(u => u.Id == id);
			if (user == null)
			{
				return Json(new { success = true, message = "Error while Locking/Unlocking" });
			}

			if (user.LockoutEnd != null && user.LockoutEnd > DateTime.Now)
			{
				user.LockoutEnd = DateTime.Now;
				_context.SaveChanges();
				return Json(new { success = true, message = "This user are unlocked!" });
			}
			else
			{
				user.LockoutEnd = DateTime.Now.AddDays(30);
				_context.SaveChanges();
				return Json(new { success = true, message = "This user are locked for 30 days!" });
			}
		}

		[HttpDelete]
		public IActionResult Delete(string? id)
		{
			ApplicationUser userToBeDeleted = _context.ApplicationUsers.FirstOrDefault(u => u.Id == id);

			_context.ApplicationUsers.Remove(userToBeDeleted);
			_context.SaveChanges();

			return Json(new { success = true, message = "Delete successful!" });
		}
		#endregion
	}
}

BulkyWeb/Areas/ViewComponents/ShoppingCartViewComponent.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyBookWeb.Areas.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(StaticDetails.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(StaticDetails.SessionCart,
                        _unitOfWork.ShoppingCartRepository.GetAll(s => s.ApplicationUserId == claim.Value).Count());
                }
                return View(HttpContext.Session.GetInt32(StaticDetails.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

BulkyWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor IHttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.7.20/sweetalert2.min.css" integrity="sha512-yX1R8uWi11xPfY7HDg7rkLL/9F1jq8Hyiz8qF4DV2nedX4IVl7ruR2+h3TFceHIcT5Oq7ooKi09UZbI39B7ylw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/loader.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
</head>
<body>
    <header class="fixed-top">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark box-shadow py-0">
            <div class="container-fluid">
                <a class="navbar-brand py-3" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 me-auto">
                        <li class="nav-item">
                            <a class="nav-link py-3" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <!--
                            <li class="nav-item">
                                <a class="nav-link py-3" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        -->
                        @if (User.IsInRole(StaticDetails.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle py-3" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu shadow">
                                    <li class="">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></hr></li>
                                    <li class="">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></hr></li>
                                    <li class="">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></hr></li>
                                    <li class="">
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li class="">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                    </li>
                                </ul>
                            </li>
                        } else
                        {
                            <li class="nav-item">
                                <a class="nav-link py-3" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            @await Component.InvokeAsync("ShoppingCart")
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3" style="padding-top: 4rem;">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container text-white-50 text-center">
            Made with <i class="bi bi-heart-fill"></i> by
            <a class="link-light link-offset-2 link-underline-opacity-0 link-underline-opacity-100-hover" href="https://github.com/iamSunHi">Sun Hi</a>
            for <u>learning purposes</u> only!
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.7.20/sweetalert2.min.js" integrity="sha512-2AOp8GEFv1X43dZpYqOp34WD+skmM18yOrCxS/S1Mh6VShz7uxlPhKmA98fsPrE7MMMtZgjshiMHKmzWtZR5uA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/g4t4lpw49wbyvwwpv8yjtn4h8fptfswo2lmvweymaqjxgkzo/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.7.20/sweetalert2.min.js" integrity="sha512-2AOp8GEFv1X43dZpYqOp34WD+skmM18yOrCxS/S1Mh6VShz7uxlPhKmA98fsPrE7MMMtZgjshiMHKmzWtZR5uA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script type="text/javascript">
		Swal.fire({
			icon: 'success',
			title: 'Done!',
			text: '@TempData["success"]',
			timer: 4000
		})
	</script>
}
@if (TempData["error"] != null)
{
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/11.7.20/sweetalert2.min.js" integrity="sha512-2AOp8GEFv1X43dZpYqOp34WD+skmM18yOrCxS/S1Mh6VShz7uxlPhKmA98fsPrE7MMMtZgjshiMHKmzWtZR5uA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script type="text/javascript">
		Swal.fire({
			icon: 'error',
			title: 'Oops...',
			text: '@TempData["error"]',
			timer: 2000
		})
	</script>
}